aspcoremvc/Controllers/NewsCategoryController.cs
using Business.Services.Panel.Interfaces;
using Common.Dto.PanelDto;
using Common.Dto.PanelDtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Controllers
{
    public class NewsCategoryController : BaseController
    {
        private readonly INewsCategoryService _newsCategoryService;
        private readonly INewsService _newsService;
        private readonly ILogger<NewsCategoryController> _logger;
        private readonly ISettingService _settingService;
        

        public NewsCategoryController(INewsCategoryService newsCategoryService, ILogger<NewsCategoryController> logger, INewsService newsService, ISettingService settingService)
        {
            _newsCategoryService = newsCategoryService;
            _logger = logger;
            _newsService = newsService;
            _settingService = settingService;
        }
        public IActionResult Index()
            
        {
            var favIcon = _settingService.GetSetting().FavIconUrl;
            ViewBag.FavIcon = favIcon;
            var categorylist = _newsCategoryService.GetAllNewsCategories();
            ViewBag.Categories = categorylist;

            return View(categorylist);
        }

        [HttpPost]
        public JsonResult AddNewsCategory(NewsCategoryDto newsCategoryDto)
        {
          
            var added = _newsCategoryService.AddNewsCategory(newsCategoryDto);
            return Json(added);
        }

        [HttpDelete]
        public IActionResult DeleteNewsCategory(int id)
        {
            
            var newsList = _newsService.GetNewsByNewsCategoryId(id);

            if (newsList.Count==0)
            {
                 var deletedNews= _newsCategoryService.DeleteNewsCategory(id);
                return Json(deletedNews);      
            }

            return Json(false);

        }


        [HttpPost]
        public  JsonResult DeleteAndAssignNewsCategory(NewsCategoryDto newsCategoryDto)
        {
            
            var deletedAndAssignedCategory = _newsCategoryService.DeleteAndAssignNewsCategory(newsCategoryDto);

            if (newsCategoryDto.Id != newsCategoryDto.NewsCategoryId)
            {
                return Json(deletedAndAssignedCategory);
            }

            return Json(false);
            
            
        }




        [HttpPost]
        public JsonResult UpdateNewsCategory(NewsCategoryDto newsCategoryDto)
        {
            var updated = _newsCategoryService.UpdateNewsCategory(newsCategoryDto);
            return Json(updated);
        }

        public JsonResult GetNewsCategoryById(int id)
        {
            var newsCategory = _newsCategoryService.GetNewsCategoryById(id);
            return Json(newsCategory);
        }
    }
}

aspcoremvc/Views/NewsCategory/Index.cshtml
@model IEnumerable<NewsCategoryDto>
@{
    ViewData["Title"] = "News";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha256-He3QEBKoL/nMXlVsoM7S2C2kjFQqS5L+mgA+F8LpG+U=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha256-R91pD48xW+oHbpJYGn5xR0Q7tMhH4xOrWn1QqMRINtA=" crossorigin="anonymous" />
<style>
    #selector[class*="sort"]:before,
    #selector[class*="sort"]:after {
        content: "" !important;
    }
</style>

<div class="az-content pd-y-20 pd-lg-y-30 pd-xl-y-40">
    <div class="container">

        <div class="az-content-body pd-lg-l-40 d-flex flex-column">

            <a class="btn" data-toggle="modal" id="btnAddCategory" style="width:180px; background-color:#5b47fb;"><strong style="color:white">Haber Kategorisi Ekle</strong> </a>


            @Html.Partial("_AddEditNewsCategory")
            @Html.Partial("_DeleteCategoryPartial")



            <hr class="mg-y-30">



            <div>
                <table id="example2" class="table">
                    <thead>
                        <tr>
                            <th>Kategori Adı</th>
                            <th id="selector"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr id="row_@item.Id">

                                <td>@item.Name</td>
                                <td>

                                    <button class="btn btn-sm btn-indigo rounded-pill" onclick="getById('@item.Id')" data-toggle="modal" data-target="#addUpdateNewsCategoryPopup"><i class="far fa-edit"></i></button>

                                    <button class="btn btn-sm btn-danger rounded-pill categoryDelete" data-name="@item.Name" data-id="@item.Id" type="submit" name="delete"><i class="far fa-trash-alt"></i></button>


                                </td>
                            </tr>
                        }



                    </tbody>
                </table>
            </div>



            <div class="ht-40"></div>


        </div><!-- az-content-body -->
    </div><!-- container -->
</div><!-- az-content -->


@section Section{

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha256-yNbKY1y6h2rbVcQtf0b8lq4a+xpktyFc3pSYoGAY1qQ=" crossorigin="anonymous"></script>




    <script type="text/javascript">
        $(document).on('click', '.categoryDelete', function () {

            var id = $(this).data("id");
            var name = $(this).data("name");

            Swal.fire({
                title: 'Emin Misin?',
                text: "Kategori Silinecek!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Evet, Sil!',
                cancelButtonText: 'İptal'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: 'delete',
                        url: '/NewsCategory/DeleteNewsCategory?Id=' + id,

                        success: function (data) {
                            if (data) {
                                $.ajax({
                                    url: "/NewsCategory/Index",
                                    type: "get",
                                    dataType: "html",
                                    contentType: "application/json; ",
                                    success: function (data) {

                                        $("#tableBody").html(data);
                                        toastr.success("İşlem başarılı bir şekilde gerçekleşti!", "Başarılı !")
                                    }

                                });
                            }

                            else {
                                toastr.error("", "İşlem gerçekleşmedi !")
                                $("#deleteNewsCategory").modal('show');
                                $("#deletedCategory").val(name);
                                $("#categoryId").val(id);

                                $("#btnRemoveAndAssign").click(function () {

                                    let id = $(categoryId).val();
                                    let newsCategoryId = $(otherCategories).val();


                                    $.ajax({
                                        type: "post",
                                        url: "/NewsCategory/DeleteAndAssignNewsCategory",
                                        dataType: "json",
                                        data: {
                                            Id: id,
                                            NewsCategoryId: newsCategoryId

                                        },
                                        cache: false,
                                        success: function (data) {
                                            if (data) {
                                                $.ajax({
                                                    url: "/NewsCategory/Index",
                                                    type: "get",
                                                    dataType: "html",
                                                    contentType: "application/json; ",
                                                    success: function (data) {
                                                        if (data) {

                                                            $("#deleteNewsCategory").modal('hide');
                                                            $("#tableBody").html(data);
                                                            toastr.success("İşlem başarılı bir şekilde gerçekleşti!", "Başarılı !")
                                                        }
                                                    }

                                                });
                                            }

                                            else {

                                                toastr.error("", "İşlem Gerçekleşmedi !")

                                            }
                                        }
                                    });
                                });
                            }
                        }
                    });

                }
            });
        });
    </script>

    <script>
        $("#btnAddCategory").on("click", function () {

            $("#categoryId").val(0);
            $("#categoryName").val("");

            $("#addUpdateNewsCategoryPopup").modal("show");

        });

    </script>

    <script>
        function getById(id) {
            $.ajax({
                url: "/NewsCategory/GetNewsCategoryById",
                type: "Get",
                contentType: "application/json; charset=utf8",
                dataType: "json",
                data: {
                    Id: id
                },
                success: function (data) {

                    $("#categoryId").val(data.Id);
                    $("#categoryName").val(data.Name);
                }
            })
        }

    </script>
    <script>

        $("#btnAddUpdateNewsCategory").click(function () {
            $("#addUpdateCategoryForm").validate({
                ignore: [],
                debug: false,
                rules: {
                    categoryname: { required: true }

                },
                messages: {
                    categoryname: { required: "Kategori Ad alanı zorunlu!" }

                },
                submitHandler: function (form) {

                    let id = $("#categoryId").val();
                    let name = $("#categoryName").val();

                    $.ajax({
                        type: "post",
                        url: id == 0 ? "/NewsCategory/AddNewsCategory" : "/NewsCategory/UpdateNewsCategory",
                        data: {
                            Id: id,
                            Name: name
                        },
                        success: function (response) {
                            if (response) {

                                $.ajax({
                                    url: "/NewsCategory/Index",
                                    type: "get",
                                    dataType: "html",
                                    contentType: "application/json; ",
                                    success: function (data) {
                                        if (data) {
                                            $("#addUpdateNewsCategoryPopup").modal('hide');

                                            $("#tableBody").html(data);
                                            toastr.success("Başarılı bir şekilde gerçekleşti!", "Başarılı !");
                                        }
                                        else {
                                            toastr.error("", "İşlem Gerçekleşmedi !");
                                        }
                                    }
                                });
                            }
                        },
                        error: function () {
                            console.log("Hata Oluştu");
                        }
                    })
                }
            });
        });
    </script>


}

aspcoremvc/Views/NewsCategory/_AddEditNewsCategory.cshtml
<style>
    .error {
        color: red;
        font-family: 'Times New Roman', Times, serif;
    }
</style>

<form id="addUpdateCategoryForm">

    <div id="addUpdateNewsCategoryPopup" class="modal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content modal-content-demo">
                <div class="modal-header">
                    <h6 class="modal-title">Haber Kategorisi</h6>
                    
                    
                </div>
                <div class="modal-body">


                    <div class="form-group row">
                        <div class="col-sm-10">
                            <input type="text" id="categoryId" style="display:none" value="" />
                        </div>

                    </div>



                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Kategori Adı</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="categoryName" name="categoryname">
                        </div>
                    </div>

                </div><!-- modal-body -->
                <div class="modal-footer">
                    <button type="submit" id="btnAddUpdateNewsCategory" class="btn btn-indigo">Kaydet</button>
                    <a asp-action="Index" asp-controller="NewsCategory" class="btn btn-outline-light">Kapat</a>
                </div>
            </div>
        </div>
    </div>


</form>

aspcoremvc/Views/NewsCategory/_DeleteCategoryPartial.cshtml
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Silinen Kategoriyle Bağlantılı Haberler Var!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="categoryId" />
               <div class="row">
                   <div class="col-md-4">
                      
                           <label id="deletedCategory"></label>
                       

                   </div>

                   <div class="col-md-8">
                       <select class="form-control" id="otherCategories">
                           @foreach (var item in ViewBag.Categories)
                           {
                               <option value="@item.Id">@item.Name</option>
                           }


                       </select>
                   </div>


               </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="btn-remove-assign" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

aspcoremvc/Views/NewsCategory/_UpdateNewsCategoryPartial.cshtml
<style>
    .error {
        color: red;
        font-family: 'Times New Roman', Times, serif;
    }
</style>

<form id="addeditcategoryform">

    <div id="updatenewscategory" class="modal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content modal-content-demo">
                <div class="modal-header">
                    <h6 class="modal-title">Haber Kategorisi</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                    <div class="form-group row">
                        <div class="col-sm-10">
                            <input type="text" id="categoryid" style="display:none" value="" />
                        </div>

                    </div>



                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Kategori Adı</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="categoryname" name="categoryname">
                        </div>
                    </div>

                </div><!-- modal-body -->
                <div class="modal-footer">
                    <button type="submit" id="addeditnewscategory" class="btn btn-indigo">Kaydet</button>
                    <a asp-action="Index" asp-controller="NewsCategory" class="btn btn-outline-light">Kapat</a>
                </div>
            </div>
        </div>
    </div>


</form>